# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'mainwindow1.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.4
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
#
#
# from PyQt5 import QtCore, QtGui, QtWidgets
#
#
# class Ui_MainWindow(object):
#     def __init__(self):
#         self.centralwidget = None
#
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(800, 600)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
#         self.groupBox.setGeometry(QtCore.QRect(80, 110, 401, 391))
#         self.groupBox.setObjectName("groupBox")
#         self.pushButton = QtWidgets.QPushButton(self.groupBox)
#         self.pushButton.setGeometry(QtCore.QRect(80, 230, 93, 28))
#         self.pushButton.setObjectName("pushButton")
#         self.widget = QtWidgets.QWidget(self.groupBox)
#         self.widget.setGeometry(QtCore.QRect(60, 40, 251, 77))
#         self.widget.setObjectName("widget")
#         self.gridLayout = QtWidgets.QGridLayout(self.widget)
#         self.gridLayout.setContentsMargins(0, 0, 0, 0)
#         self.gridLayout.setObjectName("gridLayout")
#         self.label = QtWidgets.QLabel(self.widget)
#         self.label.setObjectName("label")
#         self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
#         self.lineEdit = QtWidgets.QLineEdit(self.widget)
#         self.lineEdit.setObjectName("lineEdit")
#         self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
#         self.label_2 = QtWidgets.QLabel(self.widget)
#         self.label_2.setObjectName("label_2")
#         self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
#         self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
#         self.lineEdit_2.setObjectName("lineEdit_2")
#         self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
#         self.label_3 = QtWidgets.QLabel(self.widget)
#         self.label_3.setObjectName("label_3")
#         self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
#         self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
#         self.lineEdit_3.setObjectName("lineEdit_3")
#         self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#         self.label.setBuddy(self.lineEdit)
#         self.label_2.setBuddy(self.lineEdit_2)
#         self.label_3.setBuddy(self.lineEdit_3)
#
#         self.retranslateUi(MainWindow)
#         self.pushButton.clicked.connect(self.lineEdit_3.clear)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#         MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
#         MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
#         self.pushButton.setText(_translate("MainWindow", "关闭窗口"))
#         self.label.setText(_translate("MainWindow", "姓名(&A)"))
#         self.label_2.setText(_translate("MainWindow", "年龄(&B)"))
#         self.label_3.setText(_translate("MainWindow", "职位(&B)"))
#         self.lineEdit_3.setText(_translate("MainWindow", "想吃啥"))
#
class MyClass:
    """A simple example class"""
    i = 12345

    def f(self):
        return 'fa'
aa=MyClass
print(aa.f)